version: '3'
services:
  eap:
    image: ruslanguns/eap:3.0.5
    restart: always
    network_mode: "host"
    ports:
      - "8088:8088"
      - "8043:8043"
      - "29810:29810/udp"
      - "29811:29811"
      - "29812:29812"
      - "29813:29813"
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro

volumes:
    config:
